version: '3.8'
services:
  backend:
    build: ./demo
    container_name: backend
    networks:
      - docker-network
    depends_on:
      - postgres
    env_file:
      - app.env
    
  postgres: 
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - postgres.env
    expose:
      - 5432
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
    networks:
      - docker-network
    
  nginx: 
    image: nginx:latest
    depends_on:
      - backend
    ports: 
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    networks: 
      - docker-network
networks:
  docker-network:
    driver: bridge